version: '{build}'
image: Visual Studio 2019
before_build:
- nuget restore
- dotnet --info
- choco install opencover.portable
- choco install codecov
- choco install nunit-console-runner
build:
  project: Storm.NET.sln
  verbosity: minimal
test_script:
- OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\Storm.NET.Tests\bin\Debug\netcoreapp3.0\StormDotNet.Tests.dll" -filter:"+[Storm.NET*]* -[Storm.NET.Tests*]*" -output:".\coverage.xml"
- codecov -f "coverage.xml"